[package]
name = "common_voice_yotp"
version = "0.1.0"
authors = ["Florian Merz <flomerz@gmail.com>"]
edition = "2018"

[lib]
name = "common_voice_yotp"
path = "src/lib.rs"

[[bin]]
name = "common_voice_yotp"
path = "src/main.rs"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
glob = "0.2"
clap = "2.31"
lazy_static = "1"
phf = { version = "0.7", features = ["macros"] }
regex = "1"
failure = "0.1"
failure_derive ="0.1"
